name: criando imagens

on: push

jobs:
  criando_imagens:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3

      - name: Docker Build
        run: docker build -t bootcamp-image app/.
